### ISSUE TITLE
OwO what's this? Bwoke a thing!

### ISSUE THREAD

**Issue by ThievingWireRat** [FuelRats/EDDB_JsonAPI#2] opened 2018-04-23 20:14 UTC
http://dev.localecho.net:6543/_debug_toolbar/313430343131363636303934373336/exception

http://dev.localecho.net:6543/api/systems?filter[name:like]=%VXK%&include=bodies&nearest&x=-1000&y=-1000&z=-1000&cubesize=800&aggressive=true&type=lev&page=6

pulls

builtins.TypeError
TypeError: '<=' not supported between instances of 'int' and 'str'
Traceback (most recent call last)
File "/home/kenneaal/EDDB_JsonAPI/lib/python3.6/site-packages/pyramid_debugtoolbar/panels/performance.py", line 58, in resource_timer_handler
Display the sourcecode for this frameOpen an interactive python shell in this frameresult = handler(request)
File "/home/kenneaal/EDDB_JsonAPI/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
Display the sourcecode for this frameOpen an interactive python shell in this frameresponse = _error_handler(request, exc)
File "/home/kenneaal/EDDB_JsonAPI/lib/python3.6/site-packages/pyramid/tweens.py", line 16, in _error_handler
Display the sourcecode for this frameOpen an interactive python shell in this framereraise(*exc_info)
File "/home/kenneaal/EDDB_JsonAPI/lib/python3.6/site-packages/pyramid/compat.py", line 148, in reraise
Display the sourcecode for this frameOpen an interactive python shell in this frameraise value
File "/home/kenneaal/EDDB_JsonAPI/lib/python3.6/site-packages/pyramid/tweens.py", line 39, in excview_tween
Display the sourcecode for this frameOpen an interactive python shell in this frameresponse = handler(request)
File "/home/kenneaal/EDDB_JsonAPI/lib/python3.6/site-packages/pyramid/router.py", line 156, in handle_request
Display the sourcecode for this frameOpen an interactive python shell in this frameview_name
File "/home/kenneaal/EDDB_JsonAPI/lib/python3.6/site-packages/pyramid/view.py", line 642, in _call_view
Display the sourcecode for this frameOpen an interactive python shell in this frameresponse = view_callable(context, request)
File "/home/kenneaal/EDDB_JsonAPI/lib/python3.6/site-packages/pyramid/config/views.py", line 181, in __call__
Display the sourcecode for this frameOpen an interactive python shell in this framereturn view(context, request)
File "/home/kenneaal/EDDB_JsonAPI/lib/python3.6/site-packages/pyramid/viewderivers.py", line 390, in attr_view
Display the sourcecode for this frameOpen an interactive python shell in this framereturn view(context, request)
File "/home/kenneaal/EDDB_JsonAPI/lib/python3.6/site-packages/pyramid/viewderivers.py", line 368, in predicate_wrapper
Display the sourcecode for this frameOpen an interactive python shell in this framereturn view(context, request)
File "/home/kenneaal/EDDB_JsonAPI/lib/python3.6/site-packages/pyramid/viewderivers.py", line 439, in rendered_view
Display the sourcecode for this frameOpen an interactive python shell in this frameresult = view(context, request)
File "/home/kenneaal/EDDB_JsonAPI/lib/python3.6/site-packages/pyramid/viewderivers.py", line 124, in _class_requestonly_view
Display the sourcecode for this frameOpen an interactive python shell in this frameresponse = getattr(inst, attr)()
File "/home/kenneaal/EDDB_JsonAPI/lib/python3.6/site-packages/pyramid_jsonapi/collection_view.py", line 120, in new_func
Display the sourcecode for this frameOpen an interactive python shell in this frameif 400 <= exc.code < 500:  # pylint:disable=no-member
TypeError: '<=' not supported between instances of 'int' and 'str'
Warning: this feature should not be enabled on production systems.

Hover over any gray area in the traceback and click on the   icon on the right hand side of that gray area to show an interactive console for the associated frame. Type arbitrary Python into the console; it will be evaluated in the context of the associated frame. In the interactive console there are helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Hover over any gray area in the traceback and click on   on the right hand side of that gray area to show the source of the file associated with the frame.

Click on the traceback header to switch back and forth between the rendered version of the traceback and a plaintext copy-paste-friendly version of the traceback.

URL to recover this traceback page: http://dev.localecho.net:6543/_debug_toolbar/313430343131363636303934373336/exception

**Comment by kenneaal** [comment] 2018-04-23 20:29
This is not a valid request. You're combining no less than three different endpoint argument sets. One is for the nearest endpoint, another for the search endpoint, the third is for a JSONAPI endpoint.

Closing, not a bug.

**Closed as completed by kenneaal** 2018-04-23 20:29 UTC
